### PR TITLE
Prepare initial release to PyPI

### PR DESCRIPTION
**Pull request by justinmayer**

### CODE REVIEW

**Comment by justinmayer** [comment]
The pre-commit fix here can be ignored (I'll revert it before merging).

@rlaboiss: Any thoughts on the current state of this project before publishing the 1.0.0 release to PyPI?

**Comment by rlaboiss** [comment]
Everything looks okay, for me. You can go ahead with the official release, unless you prefer that I do it myself.

**Comment by rlaboiss** [comment]
Should I go ahead with this?

**Comment by justinmayer** [comment]
I'm annoyed that all GitHub shows my commits as inexplicably dated from 2017 even though the raw commit data clearly shows the correct June 2023 dates, but I don't think I have the energy to figure out why it's happening, much less correct them. Other than that, I think everything looks good to me.

**Comment by rlaboiss** [comment]
Yes, I noticed those wrong dated commits.

I will proceed with the release.

**Pull request merged**
